version: 2

project_name: athenzctl

before:
  hooks:
    - go mod tidy

builds:
  - id: athenzctl
    main: ./cmd/athenzctl
    binary: athenzctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fsul7o/athenzctl/internal/version.Version={{.Version}}
      - -X github.com/fsul7o/athenzctl/internal/version.Commit={{.ShortCommit}}
      - -X github.com/fsul7o/athenzctl/internal/version.Date={{.Date}}
      - -X github.com/fsul7o/athenzctl/internal/authmode.ServiceCertDefaultDNSDomain={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_SERVICECERT_DNS_DOMAIN" "" }}
      - -X github.com/fsul7o/athenzctl/internal/authmode.ServiceCertDefaultSubjectCountry={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_SERVICECERT_SUBJ_C" "" }}
      - -X github.com/fsul7o/athenzctl/internal/authmode.ServiceCertDefaultSubjectProvince={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_SERVICECERT_SUBJ_P" "" }}
      - -X github.com/fsul7o/athenzctl/internal/authmode.ServiceCertDefaultSubjectOrganization={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_SERVICECERT_SUBJ_O" "" }}
      - -X github.com/fsul7o/athenzctl/internal/authmode.ServiceCertDefaultSubjectOrganizationalUnit={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_SERVICECERT_SUBJ_OU" "" }}
      - -X github.com/fsul7o/athenzctl/internal/authmode.ServiceCertDefaultSpiffe={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_SERVICECERT_SPIFFE" "" }}
      - -X github.com/fsul7o/athenzctl/internal/authmode.ServiceCertDefaultSpiffeTrustDomain={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_SERVICECERT_SPIFFE_TRUST_DOMAIN" "" }}
      - -X github.com/fsul7o/athenzctl/internal/authmode.ServiceCertDefaultConcatIntermediateCert={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_SERVICECERT_CONCAT_INTERMEDIATE_CERT" "" }}
      - -X github.com/fsul7o/athenzctl/internal/ntokenauth.NTokenHeaderDefault={{ envOrDefault "ATHENZCTL_NTOKEN_AUTH_DEFAULT_HDR" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultDNSDomain={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_DNS_DOMAIN" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultSubjectCountry={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_SUBJ_C" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultSubjectProvince={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_SUBJ_P" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultSubjectOrganization={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_SUBJ_O" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultSubjectOrganizationalUnit={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_SUBJ_OU" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultSpiffe={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_SPIFFE" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultSpiffeTrustDomain={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_SPIFFE_TRUST_DOMAIN" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultConcatIntermediateCert={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_CONCAT_INTERMEDIATE_CERT" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultCACertBundleName={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_CACERT_BUNDLE_NAME" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultExpiryTime={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_EXPIRY_TIME" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultIP={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_IP" "" }}
      - -X github.com/fsul7o/athenzctl/internal/cli/issue.RoleCertDefaultSignerKeyID={{ envOrDefault "ATHENZCTL_ISSUE_DEFAULT_ROLECERT_SIGNER_KEY_ID" "" }}

archives:
  - id: athenzctl
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
