# This file was generated by GoReleaser. DO NOT EDIT.
cask "athenzctl" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "533d807b495041fd121cb8687fbbc981676f90ba17421fd7e04b415937e481fd"
      url "https://github.com/fsul7o/athenzctl/releases/download/v#{version}/athenzctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c7020ff61ac91e17e2c976a7698c42406fa947e2969f336af415433a68e249c"
      url "https://github.com/fsul7o/athenzctl/releases/download/v#{version}/athenzctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc12b2c74e2661f4bb0eee54bab5ca7d318ff822d641b3d9b8bb0646c182413f"
      url "https://github.com/fsul7o/athenzctl/releases/download/v#{version}/athenzctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "487a7e3a5980bf5dd938bbfed3b9c5542f53264750b20ae8d0a27e3e38d59a7a"
      url "https://github.com/fsul7o/athenzctl/releases/download/v#{version}/athenzctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "athenzctl"
  desc "A kubectl-style command-line client for Athenz"
  homepage "https://github.com/fsul7o/athenzctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athenzctl"

  # No zap stanza required

end
