# This file was generated by GoReleaser. DO NOT EDIT.
cask "athenzctl" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "f716d3e56b4c453f613583099d062285034462bf81f4dd3e0df5461b50884f4e"
      url "https://github.com/fsul7o/athenzctl/releases/download/v#{version}/athenzctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8131ea121c0916ec54fef46b6bf6fb7d68293caa41e409cf8288e5eb1d3ce7d2"
      url "https://github.com/fsul7o/athenzctl/releases/download/v#{version}/athenzctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c9c25274bddb53883464f09d09bd66e5e3828f331ba116a279ed36fbe0bd267"
      url "https://github.com/fsul7o/athenzctl/releases/download/v#{version}/athenzctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3d4caa0f9f29d848779cca2fec612efbcdd1a0142250e6b3e6c822fdf589ef1"
      url "https://github.com/fsul7o/athenzctl/releases/download/v#{version}/athenzctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "athenzctl"
  desc "A kubectl-style command-line client for Athenz"
  homepage "https://github.com/fsul7o/athenzctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athenzctl"

  # No zap stanza required

end
